"use client";

import { useState, useEffect } from "react";

interface User {
  id: string;
  email: string;
  name?: string;
  role: string;
}

// Utiliser l'environnement plutôt qu'une constante codée en dur
[00:33:39.139] Running build in Washington, D.C., USA (East) – iad1
[00:33:39.140] Build machine configuration: 2 cores, 8 GB
[00:33:39.156] Cloning github.com/Ninewashburn/creasoka (Branch: main, Commit: f6483fc)
[00:33:41.357] Cloning completed: 2.199s
[00:33:42.671] Restored build cache from previous deployment (CiArUJzoZs2ufqiCcVqH3YcYyqx9)
[00:33:44.122] Running "vercel build"
[00:33:44.605] Vercel CLI 41.7.3
[00:33:45.066] Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
[00:33:45.067] Using pnpm@10.x based on project creation date
[00:33:45.067] To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
[00:33:45.096] Installing dependencies...
[00:33:45.862] Lockfile is up to date, resolution step is skipped
[00:33:45.968] Already up to date
[00:33:46.423] 
[00:33:46.423] ╭ Warning ─────────────────────────────────────────────────────────────────────╮
[00:33:46.423] │                                                                              │
[00:33:46.424] │   Ignored build scripts: @prisma/client, @prisma/engines, prisma, sharp.     │
[00:33:46.424] │   Run "pnpm approve-builds" to pick which dependencies should be allowed     │
[00:33:46.424] │   to run scripts.                                                            │
[00:33:46.424] │                                                                              │
[00:33:46.424] ╰──────────────────────────────────────────────────────────────────────────────╯
[00:33:46.424] 
[00:33:46.455] 
[00:33:46.456] > my-v0-project@0.1.0 postinstall /vercel/path0
[00:33:46.456] > node postinstall.js
[00:33:46.456] 
[00:33:46.496] 🔄 Exécution de prisma generate...
[00:33:48.466] ✅ Génération Prisma terminée avec succès
[00:33:48.476] Done in 3.2s using pnpm v10.10.0
[00:33:48.491] Detected Next.js version: 15.2.4
[00:33:48.505] Running "pnpm run build"
[00:33:48.849] 
[00:33:48.850] > my-v0-project@0.1.0 build /vercel/path0
[00:33:48.850] > next build
[00:33:48.850] 
[00:33:49.644]    ▲ Next.js 15.2.4
[00:33:49.645] 
[00:33:49.721]    Creating an optimized production build ...
[00:34:09.921]  ✓ Compiled successfully
[00:34:10.067]    Linting and checking validity of types ...
[00:34:22.366] Failed to compile.
[00:34:22.366] 
[00:34:22.366] ./app/api/creations/route.ts:69:60
[00:34:22.367] Type error: Property 'message' does not exist on type 'object & Record<"name", unknown>'.
[00:34:22.367] 
[00:34:22.367] [0m [90m 67 |[39m       [90m// Vérifier si c'est une erreur Prisma[39m[0m
[00:34:22.367] [0m [90m 68 |[39m       [36mif[39m ([32m"name"[39m [36min[39m error [33m&&[39m error[33m.[39mname [33m===[39m [32m"PrismaClientKnownRequestError"[39m) {[0m
[00:34:22.367] [0m[31m[1m>[22m[39m[90m 69 |[39m         errorMessage [33m=[39m [32m`Erreur de base de données: ${error.message || ""}`[39m[33m;[39m[0m
[00:34:22.367] [0m [90m    |[39m                                                            [31m[1m^[22m[39m[0m
[00:34:22.367] [0m [90m 70 |[39m       }[0m
[00:34:22.367] [0m [90m 71 |[39m[0m
[00:34:22.367] [0m [90m 72 |[39m       [90m// Extraire les détails si disponibles[39m[0m
[00:34:22.421] Next.js build worker exited with code: 1 and signal: null
[00:34:22.484]  ELIFECYCLE  Command failed with exit code 1.
[00:34:22.503] Error: Command "pnpm run build" exited with 1
[00:34:22.835] 
export function useAuth() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [user, setUser] = useState<User | null>(null);

  // Vérifier l'authentification au chargement
  useEffect(() => {
    async function checkAuthStatus() {
      if (IS_DEVELOPMENT) {
        // En développement uniquement, auto-authentification
        setIsAuthenticated(true);
        setUser({
          id: "admin",
          email: "admin@creasoka.com",
          role: "admin",
        });
      } else {
        // En production, vérifier réellement l'authentification
        try {
          // Utiliser la route existante avec GET au lieu de /api/auth/check
          const response = await fetch("/api/auth", {
            method: "GET",
            credentials: "include", // Important pour envoyer les cookies
          });

          if (response.ok) {
            const data = await response.json();
            setIsAuthenticated(data.authenticated);
            if (data.authenticated) {
              setUser(data.user);
            }
          } else {
            setIsAuthenticated(false);
            setUser(null);
          }
        } catch (error) {
          console.error(
            "Erreur lors de la vérification de l'authentification:",
            error
          );
          setIsAuthenticated(false);
          setUser(null);
        }
      }
      setIsLoading(false);
    }

    checkAuthStatus();
  }, []);

  // Fonction de connexion
  const login = async (email: string, password: string): Promise<boolean> => {
    if (IS_DEVELOPMENT) {
      // En développement, accepter n'importe quels identifiants
      setIsAuthenticated(true);
      setUser({
        id: "admin",
        email: email || "admin@creasoka.com",
        role: "admin",
      });
      return true;
    }

    // En production, vérifier les identifiants
    try {
      const response = await fetch("/api/auth", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include",
        body: JSON.stringify({ email, password }),
      });

      const data = await response.json();

      if (response.ok && data.success) {
        setIsAuthenticated(true);
        setUser(data.user);
        return true;
      } else {
        console.error("Échec de la connexion:", data.message);
        return false;
      }
    } catch (error) {
      console.error("Erreur lors de la connexion:", error);
      return false;
    }
  };

  // Fonction de déconnexion
  const logout = async (): Promise<void> => {
    if (IS_DEVELOPMENT) {
      // En développement, simuler la déconnexion
      console.log("Déconnexion simulée (mode développement)");
      setIsAuthenticated(false);
      setUser(null);
      window.location.href = "/";
      return;
    }

    // En production, déconnexion réelle
    try {
      await fetch("/api/auth", {
        method: "DELETE",
        credentials: "include",
      });
    } catch (error) {
      console.error("Erreur lors de la déconnexion:", error);
    } finally {
      setIsAuthenticated(false);
      setUser(null);
      // Rediriger vers la page d'accueil après la déconnexion
      window.location.href = "/";
    }
  };

  return { isAuthenticated, isLoading, user, login, logout };
}
